# Generated by Django 4.2.7 on 2023-11-15 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='ACCIDENT_RECORD',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='VEHICLE_COLOR',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='VEHICLE_FINE_RECORD',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='VEHICLE_INSURANCE',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='VEHICLE_MILEAGE',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='VEHICLE_MODEL',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='VEHICLE_NAME',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='VEHICLE_NUMBER',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo1',
            field=models.ImageField(upload_to='static/img', verbose_name='Photo 1'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Photo 2'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Photo 3'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='static/img', verbose_name='Photo 4'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='accident_record',
            field=models.CharField(default=1, max_length=20, verbose_name='Accident Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(default=1, max_length=20, verbose_name='Vehicle Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_fine_record',
            field=models.CharField(default=1, max_length=20, verbose_name='Vehicle Fine Record'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_insurance',
            field=models.CharField(default=1, max_length=20, verbose_name='Vehicle Insurance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_mileage',
            field=models.IntegerField(default=1, verbose_name='Vehicle Mileage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(default=1, max_length=20, verbose_name='Vehicle Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Vehicle Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(default=1, max_length=20, verbose_name='Vehicle Number'),
            preserve_default=False,
        ),
    ]
