# Generated by Django 4.2.7 on 2023-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landMark',
            field=models.CharField(default='', max_length=255),
        ),
    ]
