# Generated by Django 4.2.6 on 2023-11-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bmidata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmidata',
            name='BMI',
            field=models.CharField(max_length=200),
        ),
    ]
