# Generated by Django 4.2.6 on 2023-11-04 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_persontotrainer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persontotrainer',
            unique_together={('user', 'trainer')},
        ),
    ]
