# Generated by Django 4.2.6 on 2023-11-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subscription_persontosubsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
